set_property SRC_FILE_INFO {cfile:C:/Users/jatin/Downloads/Arty-A7-100-Master.xdc rfile:../../../../Downloads/Arty-A7-100-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D9 [get_ports reset]
